source("~/workspace/NHL_regression/R/setup.R")
conn <- dbConnect(driv, dbname = "nhltest", user = "postgres",
                  password = "hollyleaf", host = "localhost")
rs <- dbSendQuery(conn, statement = "SELECT * FROM skatpred15
                  ORDER BY nhl_num;")
output <- fetch(rs, n = -1)
dbClearResult(rs)
load("~/workspace/NHL_regression/R/Goals.RData")
skaterstats <- skaterstats[, -c(3:5, 38:41)]
skaterstats$es_goals <- skaterstats$goals - skaterstats$pp_goals - skaterstats$sh_goals
cols <- c(1:6, 9:12, 15:16, 24:25, 29:30, 32:34, 38:42)
rfData <- nhlShape(2014, 2014, cols = cols, rm.nhlnum = FALSE)
gbmData <- nhlShape(2013, 2014, cols = cols, rm.nhlnum = FALSE)
rfData <- rfData[rfData$nhl_num %in% gbmData$nhl_num, ]
esgData <- as.data.frame(gbmData$nhl_num)
names(esgData)[1] <- "nhl_num"
esgData$esgrf1 <- predict(esgrfmod1, rfData)
esgData$esgrf2 <- predict(esgrfmod2, rfData)
esgData$esgrf3 <- predict(esgrfmod3, rfData)
esgData$esgrf4 <- predict(esgrfmod4, rfData)
esgData$esgrf5 <- predict(esgrfmod5, rfData)
esgData$esgrf6 <- predict(esgrfmod6, rfData)
esgData$esgrf7 <- predict(esgrfmod7, rfData)
esgData$esggbm1 <- predict(esggbmmod1, gbmData)
esgData$esggbm2 <- predict(esggbmmod2, gbmData)
esgData$esggbm3 <- predict(esggbmmod3, gbmData)
esgData$esggbm4 <- predict(esggbmmod4, gbmData)
esgData$esggbm5 <- predict(esggbmmod5, gbmData)
esgData$esggbm6 <- predict(esggbmmod6, gbmData)
esgData$esggbm7 <- predict(esggbmmod7, gbmData)
output$es_goals <- predict(esgModel, esgData)
shgData <- as.data.frame(gbmData$nhl_num)
names(shgData)[1] <- "nhl_num"
shgData$shgrf1 <- predict(shgrfmod1, rfData, type = "response")
shgData$shgrf2 <- predict(shgrfmod2, rfData, type = "response")
shgData$shgrf3 <- predict(shgrfmod3, rfData, type = "response")
shgData$shgrf4 <- predict(shgrfmod4, rfData, type = "response")
shgData$shgrf5 <- predict(shgrfmod5, rfData, type = "response")
shgData$shggbm1 <- predict(shggbmmod1, gbmData, type = "response")
shgData$shggbm2 <- predict(shggbmmod2, gbmData, type = "response")
shgData$shggbm3 <- predict(shggbmmod3, gbmData, type = "response")
shgData$shggbm4 <- predict(shggbmmod4, gbmData, type = "response")
shgData$shggbm5 <- predict(shggbmmod5, gbmData, type = "response")
output$sh_goals <- predict(shgModel, shgData, type = "response")
ppgData <- as.data.frame(gbmData$nhl_num)
names(ppgData)[1] <- "nhl_num"
ppgData$ppgrf1 <- predict(ppgrfmod1, rfData)
ppgData$ppgrf2 <- predict(ppgrfmod2, rfData)
ppgData$ppgrf3 <- predict(ppgrfmod3, rfData)
ppgData$ppgrf4 <- predict(ppgrfmod4, rfData)
ppgData$ppgrf5 <- predict(ppgrfmod5, rfData)
ppgData$ppggbm1 <- predict(ppggbmmod1, gbmData)
ppgData$ppggbm2 <- predict(ppggbmmod2, gbmData)
ppgData$ppggbm3 <- predict(ppggbmmod3, gbmData)
ppgData$ppggbm4 <- predict(ppggbmmod4, gbmData)
ppgData$ppggbm5 <- predict(ppggbmmod5, gbmData)
output$pp_goals <- predict(ppgModel, ppgData)
output$goals <- output$es_goals + output$sh_goals + output$pp_goals
dbWriteTable(conn, "skatpred15", output, overwrite=TRUE, row.names = FALSE)
dbDisconnect(conn)