source("~/workspace/NHL_regression/R/setup.R")
conn <- dbConnect(driv, dbname = "nhltest", user = "postgres",
                  password = "hollyleaf", host = "localhost")
rs <- dbSendQuery(conn, statement = "SELECT * FROM skatpred15
                  ORDER BY nhl_num;")
output <- fetch(rs, n = -1)
dbClearResult(rs)
load("~/workspace/NHL_regression/R/TOI.RData")
skaterstats <- skaterstats[, -c(3:5, 38:41)]
cols <- c(1:3, 5:6, 10, 15, 24:32, 38:41)
rfData <- nhlShape(2014, 2014, cols = cols, rm.nhlnum = FALSE)
gbmData <- nhlShape(2013, 2014, cols = cols, rm.nhlnum = FALSE)
rfData <- rfData[rfData$nhl_num %in% gbmData$nhl_num, ]
esData <- as.data.frame(gbmData$nhl_num)
names(esData)[1] <- "nhl_num"
esData$esrf1 <- predict(esrfmod1, rfData)
esData$esrf2 <- predict(esrfmod2, rfData)
esData$esrf3 <- predict(esrfmod3, rfData)
esData$esrf4 <- predict(esrfmod4, rfData)
esData$esgbm1 <- predict(esgbmmod1, gbmData)
esData$esgbm2 <- predict(esgbmmod2, gbmData)
esData$esgbm3 <- predict(esgbmmod3, gbmData)
esData$esgbm4 <- predict(esgbmmod4, gbmData)
output$es_toi <- predict(esModel, esData)
shData <- as.data.frame(esData$nhl_num)
names(shData)[1] <- "nhl_num"
shData$shrf1 <- predict(shrfmod1, rfData)
shData$shrf2 <- predict(shrfmod2, rfData)
shData$shrf3 <- predict(shrfmod3, rfData)
shData$shrf4 <- predict(shrfmod4, rfData)
shData$shgbm1 <- predict(shgbmmod1, gbmData)
shData$shgbm2 <- predict(shgbmmod2, gbmData)
shData$shgbm3 <- predict(shgbmmod3, gbmData)
shData$shgbm4 <- predict(shgbmmod4, gbmData)
output$sh_toi <- predict(shModel, shData)
ppData <- as.data.frame(esData$nhl_num)
names(ppData)[1] <- "nhl_num"
ppData$pprf1 <- predict(pprfmod1, rfData)
ppData$pprf2 <- predict(pprfmod2, rfData)
ppData$pprf3 <- predict(pprfmod3, rfData)
ppData$pprf4 <- predict(pprfmod4, rfData)
ppData$pprf5 <- predict(pprfmod5, rfData)
ppData$pprf6 <- predict(pprfmod6, rfData)
ppData$ppgbm1 <- predict(ppgbmmod1, gbmData)
ppData$ppgbm2 <- predict(ppgbmmod2, gbmData)
ppData$ppgbm3 <- predict(ppgbmmod3, gbmData)
ppData$ppgbm4 <- predict(ppgbmmod4, gbmData)
ppData$ppgbm5 <- predict(ppgbmmod5, gbmData)
ppData$ppgbm6 <- predict(ppgbmmod6, gbmData)
output$pp_toi <- predict(ppModel, ppData)
output$toi <- output$es_toi + output$sh_toi + output$pp_toi
dbWriteTable(conn, "skatpred15", output, overwrite=TRUE, row.names = FALSE)
dbDisconnect(conn)